# Imports

In [1]:
import os
os.getcwd()

'/Users/sandeepmathur/Desktop/personal/ML'

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# !pip install ucimlrepo
# from ucimlrepo import fetch_ucirepo

# Data

In [12]:
full_iris_dataset = pd.read_csv("/Users/sandeepmathur/Desktop/personal/ML/full_iris_dataset")
data = full_iris_dataset
df_data = full_iris_dataset[full_iris_dataset.columns[:4]]
df_target = pd.DataFrame(full_iris_dataset[full_iris_dataset.columns[4]])
df_data.head(5)

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [31]:
# dataset = fetch_ucirepo(id=53)
# # dataset = https://archive.ics.uci.edu/dataset/53/iris
# df_data = dataset.data.features
# df_target = dataset.data.targets
# df_data.head(5)

In [13]:
df_target.head(5)

         class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [14]:
print (df_data.shape)
print (df_target.shape)

(150, 4)
(150, 1)

In [32]:
# data = pd.concat([df_data, df_target], axis=1)
# print (data.shape)
# data.head(5)

### class --> number encoding
"Iris-setosa": 0

"Iris-versicolor": 1

"Iris-virginica": 2

In [15]:
# data_encoded = data.copy()
# data_encoded["class"] = data_encoded["class"].map({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2})
# data_encoded.head(5)

data["class"] = data["class"].map({"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2})
display(data.head(5))
data_encoded = data.copy()
display(data_encoded.head(5))
data_encoded = data_encoded.to_numpy()

   sepal length  sepal width  petal length  petal width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

   sepal length  sepal width  petal length  petal width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [16]:
# data_encoded = data_encoded.to_numpy()

print (data_encoded.shape)

np.random.seed(42)
np.random.shuffle(data_encoded)

(150, 5)

In [17]:
train = data_encoded[:int(0.8*(data_encoded.shape[0]))].T
test = data_encoded[int(0.8*(data_encoded.shape[0])):].T
# print ("0", train[0])
# print ("1", train[1])
# print ("2", train[2])
# print ("3", train[3])
# print ("4", train[4])
# print ("len", len(train[3]))

X_train, Y_train = train[:4], train[4]
X_test, Y_test = test[:4], test[4]

print ("X_train\n", X_train)
print ("Y_train\n", Y_train)
print ("X_test\n", X_test)
print ("Y_test\n", Y_test)

X_train
 [[6.1 5.7 7.7 6.  6.8 5.4 5.6 6.9 6.2 5.8 6.5 4.8 5.5 4.9 5.1 6.3 6.5 5.6
  5.7 6.4 4.7 6.1 5.  6.4 7.9 6.7 6.7 6.8 4.8 4.8 4.6 5.7 6.7 4.8 4.4 6.3
  6.4 5.2 5.  5.2 5.8 6.  6.7 5.4 5.4 5.5 6.3 6.4 6.6 7.2 5.7 7.6 5.6 5.1
  7.7 5.8 5.2 5.  5.1 5.  6.3 4.8 5.  5.1 5.6 5.1 5.7 7.7 4.6 6.2 5.7 5.5
  6.  5.8 6.  5.4 6.2 5.5 5.4 5.  6.4 5.  5.  5.5 6.7 4.9 5.8 5.  5.  5.9
  5.1 6.9 6.  6.1 7.7 5.5 4.4 4.3 6.  7.2 4.6 5.1 4.4 6.3 6.3 4.6 6.8 6.3
  4.7 6.1 6.5 6.2 7.  6.4 5.1 6.9 5.9 6.5 5.7 5.2]
 [2.8 3.8 2.6 2.9 2.8 3.4 2.9 3.1 2.2 2.7 3.2 3.  3.5 3.1 3.8 3.3 3.  2.5
  2.8 2.8 3.2 3.  3.4 2.8 3.8 3.  2.5 3.2 3.  3.1 3.6 4.4 3.1 3.4 3.2 2.5
  3.2 3.5 3.6 4.1 2.7 3.4 3.1 3.9 3.7 2.4 2.8 3.1 3.  3.6 2.9 3.  3.  3.5
  2.8 2.7 3.4 3.5 3.8 2.  2.7 3.4 3.  3.3 2.7 3.4 3.  3.8 3.2 2.9 2.5 4.2
  3.  2.7 2.2 3.  3.4 2.3 3.9 2.3 2.7 3.3 3.2 2.4 3.  3.1 2.8 3.4 3.5 3.2
  2.5 3.2 2.7 2.6 3.  2.5 2.9 3.  2.2 3.2 3.1 3.5 3.  2.5 3.4 3.4 3.  3.3
  3.2 2.9 2.8 2.8 3.2 3.2 3.8 3.1 3.  3.  2.6 2.7]
 [4.7 1.7 6.9 4.5 4.8 1.5 3.6 5.1 4.5 3.9 5.1 1.4 1.3 1.5 1.5 4.7 5.8 3.9
  4.5 5.6 1.6 4.9 1.6 5.6 6.4 5.2 5.8 5.9 1.4 1.6 1.  1.5 4.4 1.6 1.3 5.
  4.5 1.5 1.4 1.5 5.1 4.5 4.7 1.3 1.5 3.7 5.1 5.5 4.4 6.1 4.2 6.6 4.5 1.4
  6.7 4.1 1.4 1.3 1.9 3.5 4.9 1.9 1.6 1.7 4.2 1.5 4.2 6.7 1.4 4.3 5.  1.4
  4.8 5.1 4.  4.5 5.4 4.  1.7 3.3 5.3 1.4 1.2 3.8 5.  1.5 5.1 1.5 1.6 4.8
  3.  5.7 5.1 5.6 6.1 4.  1.4 1.1 5.  6.  1.5 1.4 1.3 4.9 5.6 1.4 5.5 6.
  1.3 4.7 4.6 4.8 4.7 5.3 1.6 5.4 4.2 5.2 3.5 3.9]
 [1.2 0.3 2.3 1.5 1.4 0.4 1.3 2.3 1.5 1.2 2.  0.1 0.2 0.1 0.3 1.6 2.2 1.1
  1.3 2.2 0.2 1.8 0.4 2.1 2.  2.3 1.8 2.3 0.3 0.2 0.2 0.4 1.4 0.2 0.2 1.9
  1.5 0.2 0.2 0.1 1.9 1.6 1.5 0.4 0.2 1.  1.5 1.8 1.4 2.5 1.3 2.1 1.5 0.2
  2.  1.  0.2 0.3 0.4 1.  1.8 0.2 0.2 0.5 1.3 0.2 1.2 2.2 0.2 1.3 2.  0.2
  1.8 1.9 1.  1.5 2.3 1.3 0.4 1.  1.9 0.2 0.2 1.1 1.7 0.1 2.4 0.2 0.6 1.8
  1.1 2.3 1.6 1.4 2.3 1.3 0.2 0.1 1.5 1.8 0.2 0.3 0.2 1.5 2.4 0.3 2.1 2.5
  0.2 1.4 1.5 1.8 1.4 2.3 0.2 2.1 1.5 2.  1.  1.4]]
Y_train
 [1. 0. 2. 1. 1. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0. 1. 2. 1. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 1. 0. 0. 2. 1. 0. 0. 0. 2. 1. 1. 0. 0. 1. 2. 2.
 1. 2. 1. 2. 1. 0. 2. 1. 0. 0. 0. 1. 2. 0. 0. 0. 1. 0. 1. 2. 0. 1. 2. 0.
 2. 2. 1. 1. 2. 1. 0. 1. 2. 0. 0. 1. 1. 0. 2. 0. 0. 1. 1. 2. 1. 2. 2. 1.
 0. 0. 2. 2. 0. 0. 0. 1. 2. 0. 2. 2. 0. 1. 1. 2. 1. 2. 0. 2. 1. 2. 1. 1.]
X_test
 [[6.1 4.5 6.6 5.5 5.3 5.6 7.3 6.7 5.1 4.9 6.7 7.2 4.9 6.7 4.9 6.9 7.4 6.3
  5.7 6.5 6.3 6.4 5.6 5.9 5.4 6.1 4.9 5.8 5.8 7.1]
 [3.  2.3 2.9 2.6 3.7 3.  2.9 3.3 3.7 2.4 3.3 3.  3.1 3.1 3.  3.1 2.8 2.9
  2.8 3.  2.3 2.9 2.8 3.  3.4 2.8 2.5 4.  2.6 3. ]
 [4.6 1.3 4.6 4.4 1.5 4.1 6.3 5.7 1.5 3.3 5.7 5.8 1.5 5.6 1.4 4.9 6.1 5.6
  4.1 5.5 4.4 4.3 4.9 5.1 1.7 4.  4.5 1.2 4.  5.9]
 [1.4 0.3 1.3 1.2 0.2 1.3 1.8 2.1 0.4 1.  2.5 1.6 0.1 2.4 0.2 1.5 1.9 1.8
  1.3 1.8 1.3 1.3 2.  1.8 0.2 1.3 1.7 0.2 1.2 2.1]]
Y_test
 [1. 0. 1. 1. 0. 1. 2. 2. 0. 1. 2. 2. 0. 2. 0. 1. 2. 2. 1. 2. 1. 1. 2. 2.
 0. 1. 2. 0. 1. 2.]

# Helper Functions

In [18]:
def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z, axis):
    # Z = Z - np.max(matrix, axis=1, keepdims=True)
    # return np.exp(Z) / np.sum(np.exp(Z), axis=1, keepdims=True)
    max_val = np.max(Z, axis=axis, keepdims=True)
    exponents = np.exp(Z - max_val)
    return exponents / np.sum(exponents, axis=axis, keepdims=True)

def one_hot(Y):
    Y = Y.astype(int)
    # one_hot_Y = np.zeros(( Y.size, (np.max(Y) - np.min(Y) + 1) ))   # = array with dimensions: [ (n) , (# of classes, which is 10) ]
    one_hot_Y = np.zeros(( Y.size, len(np.unique(Y)) ))   # = array with dimensions: [ (n) , (# of classes, which is 10) ]
    one_hot_Y[np.arange(Y.size), Y - np.min(Y)] = 1
    return one_hot_Y

# Core Functions

In [15]:
def init_network(num_layers, size_per_layer):
    return

def forward_prop():
    return

def back_prop():
    return

In [79]:
A2 = np.zeros((3, 10))
# y = np.array((1, 0, 0))
y = np.zeros((10, 3))
print (A2, A2.shape)
print (y, y.shape)
z = A2 - y
print ("z\n", z)
z.shape

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] (3, 10)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (10, 3)

ValueError: operands could not be broadcast together with shapes (3,10) (10,3)

# Class

In [34]:
t = np.array([1, 2, 3])
r = np.append(0, t)
r.shape

(4,)

In [50]:
t = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
r = np.array([
    [1],
    [2],
    [3],
])
t + r

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [51]:
ReLU(t)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
t = np.array([
    [1, 2, 3],
    [1, 1, 1]
])
softmax(t, axis=0)

array([[0.5       , 0.73105858, 0.88079708],
       [0.5       , 0.26894142, 0.11920292]])

In [31]:
t = [0, 1, 2]
for i in t[0:3:-1]:
    print (i)

In [57]:
t = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
    ])
print (np.sum(t, axis=1))
t

[ 3  7 11]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
np.random.randn(2, 120).shape

(2, 120)

In [252]:
r = np.array([
    [0, 1, 2],
    [1, 0, 2],
    [2, 0, 1],
    [0, 2, 1]
])
np.argmax(r, axis=1)

array([2, 2, 0, 1])

In [557]:
class NN():

    def __init__(self, X_train: np.ndarray, Y_train: np.ndarray, X_test: np.ndarray, Y_test: np.ndarray, hidden_layer_sizes: np.ndarray):
        # data should be: rows=features, cols=datapoints
        self.X_train = X_train
        # print (X_train.shape)
        self.Y_train = Y_train
        self.X_test = X_test
        self.Y_test = Y_test
        self.num_train_data_points = X_train.shape[1]
        self.num_test_data_points = X_test.shape[1]
        self.num_data_points = self.num_train_data_points + self.num_test_data_points
        self.num_hidden_layers = len(hidden_layer_sizes) # one number to indicate # of hidden layers (excluding input & output layers)
        self.total_num_layers = self.num_hidden_layers + 2
        self.layer_sizes = np.append(np.append(X_train.shape[0], hidden_layer_sizes), len(np.unique(Y_train))) # array containing every layer size (including input & output layer)
        # self.rng = np.default_rng(seed=42)
        # np.random.seed(42)

        self.init_network()

    def init_network(self):
        self.weight_matrices = [] # len = L - 1 (L = # all layers)
        self.bias_vectors = [] # len = L - 1 (L = # all layers)
        # print ("init")
        for index in range(1, self.total_num_layers):
            # print ("index", index)
            # print (self.weight_matrices.shape)
            n_out = int(self.layer_sizes[index])
            n_in = int(self.layer_sizes[index-1])
            # W1 = self.rng.uniform(low=-1.0, high=1.0, size=(self.neurons_per_layer, np.shape(X_train)[0]))
            # W = np.random.randn(n_out, n_in) # shape = [output x input]
            np.random.seed(42)
            W = np.random.randn(n_out, n_in) * np.sqrt(2.0 / n_in) # shape = [output x input]
            b = np.zeros((n_out, 1))
            # b = np.full(n_out, 1.0).reshape(n_out, 1)
            
            self.weight_matrices.append(W)
            self.bias_vectors.append(b)

            
            '''n_in = layer_sizes[i]
            n_out = layer_sizes[i+1]
            
            # He Initialization (recommended for ReLU activation)
            w = np.random.randn(n_out, n_in) * np.sqrt(2.0 / n_in)
            # Biases initialized to zero 2D column vectors
            b = np.zeros((n_out, 1))'''

    def train(self, epochs, learning_rate):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.accuracies_over_all_epochs = np.array([])
        for epoch in range(epochs):

            # print ("---------------------------------")
            # print (f"epoch: {epoch}\n")
            
            self.forward_prop()
            self.back_prop()

            # if epoch % 10 == 0:
            #     print ("---------------------------------")
            #     print (f"epoch: {epoch}")
            #     self.predict()
            #     print ()
            if epoch % 10 == 0:
                print ("---------------------------------")
                print (f"epoch: {epoch}")
                self.predict(should_print=True)
                print ()
            else:
                self.predict(should_print=False)

        print (f"epoch # and accuracy of highest accuracy epoch: {np.argmax(self.accuracies_over_all_epochs)}, {self.accuracies_over_all_epochs[np.argmax(self.accuracies_over_all_epochs)]}")
        



    # Core Functions
    
    def forward_prop(self):

        self.weighted_sum_matrices = [self.X_train] # all of the Z matrices (used for backprop)
        self.activations = [self.X_train] # training_set + activations
        
        # for (index, weight_matrix) in enumerate(self.weight_matrices):
        for index in range(self.num_hidden_layers):
            Z = self.weight_matrices[index] @ self.activations[index]
            Z += self.bias_vectors[index] # Z = linear sum --> (W @ X) + b
            # print (f"Z, index {index}\n{Z}")
            self.weighted_sum_matrices.append(Z)
            A = NN.ReLU(Z) # A = activation of Z
            # print (f"A, index {index}\n{A}")
            self.activations.append(A)

        # for the output layer
        # Z = self.weight_matrices[-1] @ self.forward_prop_inputs[-1]
        Z = self.weight_matrices[-1] @ self.activations[-1]
        Z += self.bias_vectors[-1]
        # self.weighted_sum_matrices.append(Z) # not needed?

        # print (f"Output Z\n{Z}")
        
        self.output_probability_matrix = NN.softmax(Z, axis=0).T # softmax activation instead of ReLU, shape: rows=datapoints , cols=features
        # print (f"output_probability_matrix\n{self.output_probability_matrix}")
        # self.activations.append(output_probability_matrix)

        # print ("finished forward prop")
        # print ("len(self.weighted_sum_matrices)", len(self.weighted_sum_matrices))
        # print ("len(self.activations)", len(self.activations), "\n")


        # each matrix in self.forward_prop_inputs has shape: [output_neurons x datapoints]

    def back_prop(self):
        one_hot_Y = NN.one_hot(self.Y_train) # shape: [n x c] --> rows=each datapoint , cols=each class possibility (ie. 0, 1, 2)

        assert self.output_probability_matrix.shape == one_hot_Y.shape
        error_gradient = self.output_probability_matrix - one_hot_Y # shape = [n x c]
        error_gradient = error_gradient.T # shape = [c x n]

        # print ("PRE back prop weight matrices")
        # for i in self.weight_matrices:
        #     print (i, "\n")
        # print ("\n")

        for index in range(self.total_num_layers - 2, -1, -1):
            
            # print ("backprop index", index, "\n")
            # # print ("error_gradient shape", error_gradient.shape)
            # print ("error gradient shape\n", error_gradient.shape, "\n")
            # print ("error gradient\n", error_gradient, "\n")
            
            # print ("err sum", np.sum(error_gradient, axis=1))
            # print ("err sum reshaped", np.sum(error_gradient, axis=1).T.shape)

            weighted_sum_matrix = self.weighted_sum_matrices[index]
            # activation_matrix = self.forward_prop_inputs[index].T
            activation_matrix = self.activations[index].T

            # print ("weighted_sum_matrix\n", weighted_sum_matrix, "\n")
            # print ("activation_matrix\n", activation_matrix, "\n")

            # print ("weight matrix value for sub\n", ((self.learning_rate) * (np.dot(error_gradient, activation_matrix))) / self.num_train_data_points, "\n")
            self.weight_matrices[index] -= ((self.learning_rate) * (np.dot(error_gradient, activation_matrix))) / self.num_train_data_points
            # print ("self.bias_vectors[index] shape", self.bias_vectors[index].shape)
            # print ("bias error value for subtraction shape", ((self.learning_rate) * (np.sum(error_gradient, axis=1) / self.num_train_data_points)).shape)
            self.bias_vectors[index] -= ((self.learning_rate * np.sum(error_gradient, axis=1)) / self.num_train_data_points).reshape(self.bias_vectors[index].shape[0], 1)

            error_gradient = np.dot(self.weight_matrices[index].T, error_gradient) * NN.ReLU_derivative(weighted_sum_matrix)

        # print ("POST back prop weight matrices")
        # for i in self.weight_matrices:
        #     print (i, "\n")
        # print ("\n")


    def predict(self, should_print=True):

        # A = self.X_test

        forward_prop_prediction_inputs = [self.X_test] # training_set + activations
        
        # forward propagation process
        for index in range(self.num_hidden_layers):
            # Z = self.weight_matrices[index] @ A # could just do fowrard_prop_inputs[-1], but i'll keep track using "index" for now
            Z = self.weight_matrices[index] @ forward_prop_prediction_inputs[index]
            Z += self.bias_vectors[index] # Z = linear sum --> (W @ X) + b
            A = NN.ReLU(Z) # A = activation of Z
            forward_prop_prediction_inputs.append(A)
        # for the output layer
        Z = self.weight_matrices[-1] @ forward_prop_prediction_inputs[-1]
        Z += self.bias_vectors[-1]
        self.output_probability_matrix = NN.softmax(Z.T, axis=1)

        self.output_classes = np.argmax(self.output_probability_matrix, axis=1)

        self.correct_predictions = self.output_classes == self.Y_test
        self.accuracy = sum(self.correct_predictions) / self.num_test_data_points

        self.accuracies_over_all_epochs = np.append(self.accuracies_over_all_epochs, self.accuracy)

        if should_print:
            print (f"accuracy: {self.accuracy}")

        
        
        
        


    # Helper Functions
    
    def ReLU(Z):
        return np.maximum(Z, 0)

    def ReLU_derivative(Z):
         return (Z > 0).astype(float)

    def softmax(Z, axis):
        # Z = Z - np.max(matrix, axis=1, keepdims=True)
        # return np.exp(Z) / np.sum(np.exp(Z), axis=1, keepdims=True)
        max_val = np.max(Z, axis=axis, keepdims=True)
        exponents = np.exp(Z - max_val) # to keep stable and prevent overflow
        return exponents / np.sum(exponents, axis=axis, keepdims=True)
    
    def one_hot(Y):
        Y = Y.astype(int)
        # one_hot_Y = np.zeros(( Y.size, (np.max(Y) - np.min(Y) + 1) ))   # = array with dimensions: [ (n) , (# of classes, which is 10) ]
        one_hot_Y = np.zeros(( Y.size, len(np.unique(Y)) ))   # = array with dimensions: [ (n) , (# of classes, which is 10) ]
        one_hot_Y[np.arange(Y.size), Y - np.min(Y)] = 1
        return one_hot_Y

In [379]:
for i in range(4-2, -1, -1):
    print (i)

2
1
0

In [432]:
t = np.array([
    [0, 1, 2, 3],
    [0, 1, 2, 3],
    [0, 1, 2, 3]
]).astype(float)
# np.sum(t, axis=1).T.shape
# t[0] -= (10 * np.array([3, 3, 3, 3])) / 5
t += np.array([[1], [2], [3]])
t

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

# Testing Class

In [504]:
for i in test.weight_matrices:
    print (i.shape)
    print (i, "\n")

(2, 4)
[[nan nan nan nan]
 [nan nan nan nan]]

(2, 2)
[[nan nan]
 [nan nan]]

(3, 2)
[[nan nan]
 [nan nan]
 [nan nan]]

In [558]:
test = NN(X_train=X_train, Y_train=Y_train, X_test=X_test, Y_test=Y_test, hidden_layer_sizes=np.array([5, 5]))
print ("initialized")
# test.train(epochs=1, learning_rate=1)
test.train(epochs=75, learning_rate=0.05)
# test.predict()

initialized
---------------------------------
epoch: 0
accuracy: 0.36666666666666664

---------------------------------
epoch: 10
accuracy: 0.6

---------------------------------
epoch: 20
accuracy: 0.6

---------------------------------
epoch: 30
accuracy: 0.6

---------------------------------
epoch: 40
accuracy: 0.6

---------------------------------
epoch: 50
accuracy: 0.5666666666666667

---------------------------------
epoch: 60
accuracy: 0.6333333333333333

---------------------------------
epoch: 70
accuracy: 0.7333333333333333

epoch # and accuracy of highest accuracy epoch: 69, 0.9666666666666667

In [554]:
test.predict()

accuracy: 0.8666666666666667

In [360]:
test = NN(X_train=X_train, Y_train=Y_train, X_test=X_test, Y_test=Y_test, hidden_layer_sizes=np.array([2, 2]))
# test.train(epochs=1, learning_rate=0.5)

In [335]:
y = 1
u = 2
for i in range(5):
    a = y + u
print ("done", y)
a = y + u
print ("after", y)

done 1
after 1

In [361]:
test.train(epochs=10, learning_rate=1)
test.predict()

ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,3)

In [320]:
test.output_probability_matrix

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.3294678 , 0.29388458, 0.37664762],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.32821447, 0.28573348, 0.38605204],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33195256, 0.31474191, 0.35330553],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33306317, 0.32874464, 0.33819219],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33283731, 0.32539906, 0.34176363]])

In [276]:
test.output_probability_matrix.shape

(3, 30)

In [266]:
test.output_classes

array([ 1, 13,  1])

## Testing Code in Class

In [239]:
test.train(epochs=1, learning_rate=0.5)

w shape (4, 120)
forward_prop_inputs shape (4, 120)
w shape (2, 120)
forward_prop_inputs shape (2, 120)
w shape (2, 120)
forward_prop_inputs shape (2, 120)
w shape (3, 120)
forward_prop_inputs shape (3, 120)

ValueError: operands could not be broadcast together with shapes (120,3) (2,)

In [249]:
for i in test.weight_matrices:
    print (i.shape)

(2, 4)
(2, 2)
(3, 2)

In [240]:
test.probability_matrix.shape

AttributeError: 'NN' object has no attribute 'probability_matrix'

In [203]:
test.layer_sizes

array([4, 2, 2, 3])

In [213]:
len(test.forward_prop_inputs)

4

In [221]:
test.forward_prop_inputs[1].shape

(2, 120)

In [233]:
test.forward_prop()

# w shape should be [2 x 4], not [2 x 120] --> 120 is NOT input

w shape (4, 120)
forward_prop_inputs shape (4, 120)
w shape (2, 120)
forward_prop_inputs shape (2, 120)
w shape (2, 120)
forward_prop_inputs shape (2, 120)
w shape (3, 120)
forward_prop_inputs shape (3, 120)

In [188]:
r = np.array([1, 2])
t = np.array([[3], [4]])
print (r.shape)
print (t.shape)
r @ t

(2,)
(2, 1)

array([11])

# Digit Recognizer Data

In [7]:
data2 = pd.read_csv("/Users/ronitmathur/Desktop/personal/ML/digit-recognizer/train.csv")

In [10]:
data2.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
data2.shape

(42000, 785)

In [3]:
data = pd.read_csv("/Users/ronitmathur/Desktop/personal/ML/digit-recognizer/train.csv")

In [4]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T   # "development/validaiton set"
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [23]:
X_train.shape

(784, 41000)

In [22]:
counter = 0
for i in range(len(data2)):
    # print (i)
    print (max(data2.loc[i]))
    counter += 1
print (counter)

255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
254
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
254
254
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
254
255
255
255
255
255
254
255
255
255
255
255
255
255
254
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
254
255
255
254
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
254
254
255
255
254
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
254
254
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
254
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
254
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
254
255
255
255
255
255
255
254
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
254
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
254
255
255
254
254
255
254
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
254
254
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
254
254
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
254
255
255
255
255
255
255
254
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
254
254
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
254
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
254
254
254
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
254
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
254
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
254
255
255
255
255
254
255
255
254
255
255
254
255
255
254
255
255
254
255
255
255
255
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
254
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
254
254
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
254
254
255
255
255
255
254
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
255
254
255
255
254
255
254
255
255
254
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
254
254
255
254
254
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
254
254
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
254
255
254
255
255
255
255
254
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255

In [28]:
W1 = np.random.rand(10, 784)

One-Hot Encoded Vector Format:
Cat[1, 0, 0]
Dog[0, 1, 0]
Bird[0, 0, 1]