# Imports

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from datetime import datetime

from Feed_Forward_NN_Class import NN

# NN-Wrapper Class

In [9]:
class model(NN):
    def __init__(self, X_train: np.ndarray, Y_train: np.ndarray, X_test: np.ndarray, Y_test: np.ndarray, hidden_layer_sizes: np.ndarray):
        super().__init__(X_train, Y_train, X_test, Y_test, hidden_layer_sizes)

    def save_model(self):
        return

# Digits Data

## Train Data

In [2]:
digit_train_data = pd.read_csv("Data/digit-recognizer/train.csv")
print (digit_train_data.shape)
digit_train_data.head(5)

(42000, 785)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
digit_train, digit_test = digit_train_data.iloc[:, 1:].to_numpy(), digit_train_data.iloc[:, 0].to_numpy()
digit_X_train, digit_X_test, digit_Y_train, digit_Y_test = train_test_split(digit_train, digit_test, test_size=0.2, random_state=42, stratify=digit_test)
print (digit_X_train.shape, "\n", digit_Y_train.shape)

(33600, 784)
 (33600,)

In [4]:
# standardizing data
scaler = StandardScaler()
digit_X_train_scaled = scaler.fit_transform(digit_X_train)
# digit_X_test_scaled = scaler.fit_transform(digit_X_test)
digit_X_test_scaled = scaler.transform(digit_X_test)

In [5]:
digit_X_train_scaled = digit_X_train_scaled.T # shape now = [classes x n]
digit_Y_train = digit_Y_train.T # shape now = [1 row x n cols]
digit_X_test_scaled = digit_X_test_scaled.T # shape now = [classes x n]
digit_Y_test = digit_Y_test.T # shape now = [1 row x n cols]
print (digit_X_train_scaled.shape, "\n", digit_Y_train.shape)

(784, 33600)
 (33600,)

## Test Data

In [6]:
digit_test_data = pd.read_csv("Data/digit-recognizer/test.csv")
print (digit_test_data.shape)
digit_test_data.head(5)

(28000, 784)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
digit_test_data = digit_test_data.to_numpy()
print (digit_test_data.shape, "\n")
digit_test_data_scaled = scaler.transform(digit_test_data)
digit_test_data_scaled = digit_test_data_scaled.T
print (np.mean(digit_test_data_scaled), digit_test_data_scaled.shape)

(28000, 784)

-0.0012535122916919287 (784, 28000)

# Training Models

In [18]:
# base_model = NN(X_train=digit_X_train_scaled, Y_train=digit_Y_train, X_test=digit_X_test_scaled, Y_test=digit_Y_test, hidden_layer_sizes=np.array([50, 25]))
base_model = model(X_train=digit_X_train_scaled, Y_train=digit_Y_train, X_test=digit_X_test_scaled, Y_test=digit_Y_test, hidden_layer_sizes=np.array([50, 25]))

Initializing Network
Initializing Learnable Parameters
Learnable Parameters Initialized
Initializing Model Functions
Model Functions Initialized - change as needed
Network Initialized

In [19]:
base_model.train(epochs=150, learning_rate=0.1)

layer 0: 49.97% dead neurons
layer 1: 43.87% dead neurons
---------------------------------
Epoch: 0
Accuracy: 0.17011904761904761
Loss: 3.1281096343780077
layer 0: 50.13% dead neurons
layer 1: 46.08% dead neurons
layer 0: 50.31% dead neurons
layer 1: 47.04% dead neurons
layer 0: 50.49% dead neurons
layer 1: 47.49% dead neurons
layer 0: 50.66% dead neurons
layer 1: 47.72% dead neurons
layer 0: 50.79% dead neurons
layer 1: 47.80% dead neurons
layer 0: 50.90% dead neurons
layer 1: 47.82% dead neurons
layer 0: 50.99% dead neurons
layer 1: 47.77% dead neurons
layer 0: 51.07% dead neurons
layer 1: 47.65% dead neurons
layer 0: 51.14% dead neurons
layer 1: 47.51% dead neurons
layer 0: 51.20% dead neurons
layer 1: 47.33% dead neurons
---------------------------------
Epoch: 10
Accuracy: 0.6970238095238095
Loss: 1.1522594726038646
layer 0: 51.24% dead neurons
layer 1: 47.14% dead neurons
layer 0: 51.28% dead neurons
layer 1: 46.94% dead neurons
layer 0: 51.31% dead neurons
layer 1: 46.73% dead neurons
layer 0: 51.34% dead neurons
layer 1: 46.49% dead neurons
layer 0: 51.37% dead neurons
layer 1: 46.26% dead neurons
layer 0: 51.38% dead neurons
layer 1: 46.03% dead neurons
layer 0: 51.39% dead neurons
layer 1: 45.79% dead neurons
layer 0: 51.40% dead neurons
layer 1: 45.57% dead neurons
layer 0: 51.42% dead neurons
layer 1: 45.36% dead neurons
layer 0: 51.43% dead neurons
layer 1: 45.15% dead neurons
---------------------------------
Epoch: 20
Accuracy: 0.8061904761904762
Loss: 0.7425007670923307
layer 0: 51.43% dead neurons
layer 1: 44.93% dead neurons
layer 0: 51.44% dead neurons
layer 1: 44.73% dead neurons
layer 0: 51.44% dead neurons
layer 1: 44.54% dead neurons
layer 0: 51.44% dead neurons
layer 1: 44.36% dead neurons
layer 0: 51.44% dead neurons
layer 1: 44.19% dead neurons
layer 0: 51.45% dead neurons
layer 1: 44.03% dead neurons
layer 0: 51.45% dead neurons
layer 1: 43.87% dead neurons
layer 0: 51.45% dead neurons
layer 1: 43.71% dead neurons
layer 0: 51.45% dead neurons
layer 1: 43.56% dead neurons
layer 0: 51.44% dead neurons
layer 1: 43.43% dead neurons
---------------------------------
Epoch: 30
Accuracy: 0.8466666666666667
Loss: 0.5610020630916147
layer 0: 51.44% dead neurons
layer 1: 43.30% dead neurons
layer 0: 51.44% dead neurons
layer 1: 43.18% dead neurons
layer 0: 51.43% dead neurons
layer 1: 43.06% dead neurons
layer 0: 51.43% dead neurons
layer 1: 42.94% dead neurons
layer 0: 51.43% dead neurons
layer 1: 42.83% dead neurons
layer 0: 51.43% dead neurons
layer 1: 42.73% dead neurons
layer 0: 51.42% dead neurons
layer 1: 42.63% dead neurons
layer 0: 51.42% dead neurons
layer 1: 42.53% dead neurons
layer 0: 51.41% dead neurons
layer 1: 42.44% dead neurons
layer 0: 51.41% dead neurons
layer 1: 42.35% dead neurons
---------------------------------
Epoch: 40
Accuracy: 0.8673809523809524
Loss: 0.46929418120634014
layer 0: 51.40% dead neurons
layer 1: 42.26% dead neurons
layer 0: 51.40% dead neurons
layer 1: 42.18% dead neurons
layer 0: 51.39% dead neurons
layer 1: 42.09% dead neurons
layer 0: 51.39% dead neurons
layer 1: 42.01% dead neurons
layer 0: 51.38% dead neurons
layer 1: 41.94% dead neurons
layer 0: 51.38% dead neurons
layer 1: 41.87% dead neurons
layer 0: 51.37% dead neurons
layer 1: 41.79% dead neurons
layer 0: 51.36% dead neurons
layer 1: 41.72% dead neurons
layer 0: 51.35% dead neurons
layer 1: 41.66% dead neurons
layer 0: 51.35% dead neurons
layer 1: 41.59% dead neurons
---------------------------------
Epoch: 50
Accuracy: 0.8795238095238095
Loss: 0.4137230387653013
layer 0: 51.34% dead neurons
layer 1: 41.52% dead neurons
layer 0: 51.34% dead neurons
layer 1: 41.46% dead neurons
layer 0: 51.33% dead neurons
layer 1: 41.40% dead neurons
layer 0: 51.32% dead neurons
layer 1: 41.33% dead neurons
layer 0: 51.31% dead neurons
layer 1: 41.28% dead neurons
layer 0: 51.31% dead neurons
layer 1: 41.23% dead neurons
layer 0: 51.30% dead neurons
layer 1: 41.18% dead neurons
layer 0: 51.29% dead neurons
layer 1: 41.13% dead neurons
layer 0: 51.29% dead neurons
layer 1: 41.07% dead neurons
layer 0: 51.29% dead neurons
layer 1: 41.02% dead neurons
---------------------------------
Epoch: 60
Accuracy: 0.8878571428571429
Loss: 0.3755690420593735
layer 0: 51.28% dead neurons
layer 1: 40.98% dead neurons
layer 0: 51.27% dead neurons
layer 1: 40.93% dead neurons
layer 0: 51.27% dead neurons
layer 1: 40.89% dead neurons
layer 0: 51.26% dead neurons
layer 1: 40.85% dead neurons
layer 0: 51.26% dead neurons
layer 1: 40.80% dead neurons
layer 0: 51.24% dead neurons
layer 1: 40.75% dead neurons
layer 0: 51.24% dead neurons
layer 1: 40.72% dead neurons
layer 0: 51.23% dead neurons
layer 1: 40.68% dead neurons
layer 0: 51.23% dead neurons
layer 1: 40.63% dead neurons
layer 0: 51.22% dead neurons
layer 1: 40.59% dead neurons
---------------------------------
Epoch: 70
Accuracy: 0.8948809523809523
Loss: 0.34719149672291305
layer 0: 51.22% dead neurons
layer 1: 40.55% dead neurons
layer 0: 51.21% dead neurons
layer 1: 40.51% dead neurons
layer 0: 51.20% dead neurons
layer 1: 40.47% dead neurons
layer 0: 51.19% dead neurons
layer 1: 40.43% dead neurons
layer 0: 51.19% dead neurons
layer 1: 40.40% dead neurons
layer 0: 51.18% dead neurons
layer 1: 40.36% dead neurons
layer 0: 51.17% dead neurons
layer 1: 40.32% dead neurons
layer 0: 51.16% dead neurons
layer 1: 40.29% dead neurons
layer 0: 51.16% dead neurons
layer 1: 40.26% dead neurons
layer 0: 51.15% dead neurons
layer 1: 40.22% dead neurons
---------------------------------
Epoch: 80
Accuracy: 0.9
Loss: 0.3247446130906889
layer 0: 51.14% dead neurons
layer 1: 40.19% dead neurons
layer 0: 51.13% dead neurons
layer 1: 40.16% dead neurons
layer 0: 51.13% dead neurons
layer 1: 40.12% dead neurons
layer 0: 51.12% dead neurons
layer 1: 40.09% dead neurons
layer 0: 51.11% dead neurons
layer 1: 40.06% dead neurons
layer 0: 51.11% dead neurons
layer 1: 40.03% dead neurons
layer 0: 51.10% dead neurons
layer 1: 39.99% dead neurons
layer 0: 51.10% dead neurons
layer 1: 39.96% dead neurons
layer 0: 51.09% dead neurons
layer 1: 39.93% dead neurons
layer 0: 51.08% dead neurons
layer 1: 39.90% dead neurons
---------------------------------
Epoch: 90
Accuracy: 0.9039285714285714
Loss: 0.30633740057391184
layer 0: 51.08% dead neurons
layer 1: 39.87% dead neurons
layer 0: 51.07% dead neurons
layer 1: 39.84% dead neurons
layer 0: 51.06% dead neurons
layer 1: 39.81% dead neurons
layer 0: 51.05% dead neurons
layer 1: 39.78% dead neurons
layer 0: 51.04% dead neurons
layer 1: 39.75% dead neurons
layer 0: 51.04% dead neurons
layer 1: 39.72% dead neurons
layer 0: 51.03% dead neurons
layer 1: 39.69% dead neurons
layer 0: 51.03% dead neurons
layer 1: 39.66% dead neurons
layer 0: 51.02% dead neurons
layer 1: 39.63% dead neurons
layer 0: 51.02% dead neurons
layer 1: 39.61% dead neurons
---------------------------------
Epoch: 100
Accuracy: 0.9073809523809524
Loss: 0.2907525994974306
layer 0: 51.01% dead neurons
layer 1: 39.58% dead neurons
layer 0: 51.00% dead neurons
layer 1: 39.56% dead neurons
layer 0: 51.00% dead neurons
layer 1: 39.53% dead neurons
layer 0: 50.99% dead neurons
layer 1: 39.50% dead neurons
layer 0: 50.98% dead neurons
layer 1: 39.47% dead neurons
layer 0: 50.98% dead neurons
layer 1: 39.44% dead neurons
layer 0: 50.97% dead neurons
layer 1: 39.41% dead neurons
layer 0: 50.96% dead neurons
layer 1: 39.38% dead neurons
layer 0: 50.95% dead neurons
layer 1: 39.36% dead neurons
layer 0: 50.95% dead neurons
layer 1: 39.33% dead neurons
---------------------------------
Epoch: 110
Accuracy: 0.9103571428571429
Loss: 0.2773176186915888
layer 0: 50.94% dead neurons
layer 1: 39.31% dead neurons
layer 0: 50.93% dead neurons
layer 1: 39.28% dead neurons
layer 0: 50.93% dead neurons
layer 1: 39.25% dead neurons
layer 0: 50.92% dead neurons
layer 1: 39.23% dead neurons
layer 0: 50.92% dead neurons
layer 1: 39.20% dead neurons
layer 0: 50.91% dead neurons
layer 1: 39.18% dead neurons
layer 0: 50.91% dead neurons
layer 1: 39.15% dead neurons
layer 0: 50.90% dead neurons
layer 1: 39.12% dead neurons
layer 0: 50.89% dead neurons
layer 1: 39.10% dead neurons
layer 0: 50.89% dead neurons
layer 1: 39.08% dead neurons
---------------------------------
Epoch: 120
Accuracy: 0.9127380952380952
Loss: 0.2655738631516416
layer 0: 50.88% dead neurons
layer 1: 39.05% dead neurons
layer 0: 50.88% dead neurons
layer 1: 39.03% dead neurons
layer 0: 50.87% dead neurons
layer 1: 39.01% dead neurons
layer 0: 50.87% dead neurons
layer 1: 38.98% dead neurons
layer 0: 50.86% dead neurons
layer 1: 38.96% dead neurons
layer 0: 50.86% dead neurons
layer 1: 38.93% dead neurons
layer 0: 50.85% dead neurons
layer 1: 38.91% dead neurons
layer 0: 50.85% dead neurons
layer 1: 38.89% dead neurons
layer 0: 50.84% dead neurons
layer 1: 38.86% dead neurons
layer 0: 50.84% dead neurons
layer 1: 38.84% dead neurons
---------------------------------
Epoch: 130
Accuracy: 0.915952380952381
Loss: 0.2550794515983511
layer 0: 50.83% dead neurons
layer 1: 38.81% dead neurons
layer 0: 50.83% dead neurons
layer 1: 38.79% dead neurons
layer 0: 50.82% dead neurons
layer 1: 38.76% dead neurons
layer 0: 50.81% dead neurons
layer 1: 38.74% dead neurons
layer 0: 50.81% dead neurons
layer 1: 38.71% dead neurons
layer 0: 50.81% dead neurons
layer 1: 38.69% dead neurons
layer 0: 50.80% dead neurons
layer 1: 38.67% dead neurons
layer 0: 50.80% dead neurons
layer 1: 38.65% dead neurons
layer 0: 50.79% dead neurons
layer 1: 38.63% dead neurons
layer 0: 50.79% dead neurons
layer 1: 38.60% dead neurons
---------------------------------
Epoch: 140
Accuracy: 0.9177380952380952
Loss: 0.24563383426917917
layer 0: 50.79% dead neurons
layer 1: 38.58% dead neurons
layer 0: 50.78% dead neurons
layer 1: 38.56% dead neurons
layer 0: 50.78% dead neurons
layer 1: 38.54% dead neurons
layer 0: 50.78% dead neurons
layer 1: 38.52% dead neurons
layer 0: 50.77% dead neurons
layer 1: 38.50% dead neurons
layer 0: 50.77% dead neurons
layer 1: 38.48% dead neurons
layer 0: 50.77% dead neurons
layer 1: 38.46% dead neurons
layer 0: 50.76% dead neurons
layer 1: 38.44% dead neurons
layer 0: 50.75% dead neurons
layer 1: 38.42% dead neurons


 Highest Accuracy:
	Epoch # = 149
	Accuracy = 0.9197619047619048
	Loss = 0.23791510735741617

In [69]:
base_model.train(epochs=300, learning_rate=1)

layer 0: 49.97% dead neurons
layer 1: 43.87% dead neurons

ValueError: operands could not be broadcast together with shapes (33600,10) (8400,)

# Prediction

In [47]:
base_model_predictions = base_model.predict(X_data=digit_test_data_scaled)
base_model_predictions.shape

(28000,)

In [48]:
# ---Kaggle Submission---

# flatten and ensure predictions are integers (0 instead of 0.0)
final_predictions = np.asarray(base_model_predictions).flatten().astype(int)

# create df and shift the index to start at 1 (kaggle required format)
df = pd.DataFrame({'Label': final_predictions})
df.index = df.index + 1

# save to a CSV
curr_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
df.to_csv(f"/Users/ronitmathur/Desktop/ML/Feed-Forward_NN/Kaggle/base_model_submission_{curr_time}.csv", index_label='ImageId')