# Imports

In [17]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from datetime import datetime

from Feed_Forward_NN_Class import NN

# NN-Wrapper Class

In [60]:
class model(NN):
    def __init__(self, X_train: np.ndarray, Y_train: np.ndarray, X_test: np.ndarray, Y_test: np.ndarray, hidden_layer_sizes: np.ndarray):
        super().__init__(X_train, Y_train, X_test, Y_test, hidden_layer_sizes)

    def save_model(self):
        return

# Digits Data

## Train Data

In [3]:
digit_train_data = pd.read_csv("Data/digit-recognizer/train.csv")
print (digit_train_data.shape)
digit_train_data.head(5)

(42000, 785)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
digit_train, digit_test = digit_train_data.iloc[:, 1:].to_numpy(), digit_train_data.iloc[:, 0].to_numpy()
digit_X_train, digit_X_test, digit_Y_train, digit_Y_test = train_test_split(digit_train, digit_test, test_size=0.2, random_state=42, stratify=digit_test)
print (digit_X_train.shape, "\n", digit_Y_train.shape)

(33600, 784)
 (33600,)

In [5]:
# standardizing data
scaler = StandardScaler()
digit_X_train_scaled = scaler.fit_transform(digit_X_train)
# digit_X_test_scaled = scaler.fit_transform(digit_X_test)
digit_X_test_scaled = scaler.transform(digit_X_test)

In [6]:
digit_X_train_scaled = digit_X_train_scaled.T # shape now = [classes x n]
digit_Y_train = digit_Y_train.T # shape now = [1 row x n cols]
digit_X_test_scaled = digit_X_test_scaled.T # shape now = [classes x n]
digit_Y_test = digit_Y_test.T # shape now = [1 row x n cols]
print (digit_X_train_scaled.shape, "\n", digit_Y_train.shape)

(784, 33600)
 (33600,)

## Test Data

In [7]:
digit_test_data = pd.read_csv("Data/digit-recognizer/test.csv")
print (digit_test_data.shape)
digit_test_data.head(5)

(28000, 784)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
digit_test_data = digit_test_data.to_numpy()
print (digit_test_data.shape, "\n")
digit_test_data_scaled = scaler.transform(digit_test_data)
digit_test_data_scaled = digit_test_data_scaled.T
print (np.mean(digit_test_data_scaled), digit_test_data_scaled.shape)

(28000, 784)

-0.0012535122916919287 (784, 28000)

# Training Models

In [50]:
# base_model = NN(X_train=digit_X_train_scaled, Y_train=digit_Y_train, X_test=digit_X_test_scaled, Y_test=digit_Y_test, hidden_layer_sizes=np.array([50, 25]))
base_model = model(X_train=digit_X_train_scaled, Y_train=digit_Y_train, X_test=digit_X_test_scaled, Y_test=digit_Y_test, hidden_layer_sizes=np.array([50, 25]))

Initializing Network
Network Initialized

In [10]:
base_model.train(epochs=150, learning_rate=0.1)

---------------------------------
epoch: 0
accuracy: 0.17226190476190475
---------------------------------
epoch: 10
accuracy: 0.6992857142857143
---------------------------------
epoch: 20
accuracy: 0.8077380952380953
---------------------------------
epoch: 30
accuracy: 0.8473809523809523
---------------------------------
epoch: 40
accuracy: 0.8679761904761905
---------------------------------
epoch: 50
accuracy: 0.8794047619047619
---------------------------------
epoch: 60
accuracy: 0.8879761904761905
---------------------------------
epoch: 70
accuracy: 0.8945238095238095
---------------------------------
epoch: 80
accuracy: 0.8994047619047619
---------------------------------
epoch: 90
accuracy: 0.9033333333333333
---------------------------------
epoch: 100
accuracy: 0.9078571428571428
---------------------------------
epoch: 110
accuracy: 0.9105952380952381
---------------------------------
epoch: 120
accuracy: 0.9129761904761905
---------------------------------
epoch: 130
accuracy: 0.9155952380952381
---------------------------------
epoch: 140
accuracy: 0.9175


 Highest Accuracy:
	Epoch # = 149
	Accuracy = 0.9192857142857143

In [51]:
base_model.train(epochs=300, learning_rate=1)

layer 0: 49.97% dead neurons
layer 1: 43.91% dead neurons
---------------------------------
epoch: 0
accuracy: 0.42404761904761906
layer 0: 52.10% dead neurons
layer 1: 61.66% dead neurons
layer 0: 48.91% dead neurons
layer 1: 65.40% dead neurons
layer 0: 49.96% dead neurons
layer 1: 69.30% dead neurons
layer 0: 50.08% dead neurons
layer 1: 73.61% dead neurons
layer 0: 52.00% dead neurons
layer 1: 75.31% dead neurons
layer 0: 53.06% dead neurons
layer 1: 78.81% dead neurons
layer 0: 53.56% dead neurons
layer 1: 78.45% dead neurons
layer 0: 53.78% dead neurons
layer 1: 76.13% dead neurons
layer 0: 53.76% dead neurons
layer 1: 76.11% dead neurons
layer 0: 53.92% dead neurons
layer 1: 74.92% dead neurons
---------------------------------
epoch: 10
accuracy: 0.7908333333333334
layer 0: 53.71% dead neurons
layer 1: 77.80% dead neurons
layer 0: 53.93% dead neurons
layer 1: 77.12% dead neurons
layer 0: 53.93% dead neurons
layer 1: 75.87% dead neurons
layer 0: 53.91% dead neurons
layer 1: 75.32% dead neurons
layer 0: 53.84% dead neurons
layer 1: 74.61% dead neurons
layer 0: 53.79% dead neurons
layer 1: 74.34% dead neurons
layer 0: 53.71% dead neurons
layer 1: 73.83% dead neurons
layer 0: 53.65% dead neurons
layer 1: 73.69% dead neurons
layer 0: 53.59% dead neurons
layer 1: 73.25% dead neurons
layer 0: 53.55% dead neurons
layer 1: 73.17% dead neurons
---------------------------------
epoch: 20
accuracy: 0.9058333333333334
layer 0: 53.48% dead neurons
layer 1: 72.76% dead neurons
layer 0: 53.44% dead neurons
layer 1: 72.71% dead neurons
layer 0: 53.39% dead neurons
layer 1: 72.35% dead neurons
layer 0: 53.35% dead neurons
layer 1: 72.32% dead neurons
layer 0: 53.31% dead neurons
layer 1: 71.98% dead neurons
layer 0: 53.26% dead neurons
layer 1: 71.95% dead neurons
layer 0: 53.22% dead neurons
layer 1: 71.62% dead neurons
layer 0: 53.18% dead neurons
layer 1: 71.60% dead neurons
layer 0: 53.14% dead neurons
layer 1: 71.27% dead neurons
layer 0: 53.11% dead neurons
layer 1: 71.26% dead neurons
---------------------------------
epoch: 30
accuracy: 0.9217857142857143
layer 0: 53.07% dead neurons
layer 1: 70.93% dead neurons
layer 0: 53.04% dead neurons
layer 1: 70.92% dead neurons
layer 0: 53.00% dead neurons
layer 1: 70.61% dead neurons
layer 0: 52.97% dead neurons
layer 1: 70.59% dead neurons
layer 0: 52.94% dead neurons
layer 1: 70.29% dead neurons
layer 0: 52.91% dead neurons
layer 1: 70.29% dead neurons
layer 0: 52.88% dead neurons
layer 1: 69.99% dead neurons
layer 0: 52.85% dead neurons
layer 1: 70.01% dead neurons
layer 0: 52.82% dead neurons
layer 1: 69.70% dead neurons
layer 0: 52.79% dead neurons
layer 1: 69.72% dead neurons
---------------------------------
epoch: 40
accuracy: 0.9319047619047619
layer 0: 52.77% dead neurons
layer 1: 69.40% dead neurons
layer 0: 52.75% dead neurons
layer 1: 69.47% dead neurons
layer 0: 52.71% dead neurons
layer 1: 69.13% dead neurons
layer 0: 52.69% dead neurons
layer 1: 69.23% dead neurons
layer 0: 52.66% dead neurons
layer 1: 68.88% dead neurons
layer 0: 52.64% dead neurons
layer 1: 69.02% dead neurons
layer 0: 52.62% dead neurons
layer 1: 68.63% dead neurons
layer 0: 52.60% dead neurons
layer 1: 68.83% dead neurons
layer 0: 52.58% dead neurons
layer 1: 68.38% dead neurons
layer 0: 52.56% dead neurons
layer 1: 68.66% dead neurons
---------------------------------
epoch: 50
accuracy: 0.9328571428571428
layer 0: 52.56% dead neurons
layer 1: 68.15% dead neurons
layer 0: 52.53% dead neurons
layer 1: 68.53% dead neurons
layer 0: 52.52% dead neurons
layer 1: 67.95% dead neurons
layer 0: 52.51% dead neurons
layer 1: 68.44% dead neurons
layer 0: 52.50% dead neurons
layer 1: 67.76% dead neurons
layer 0: 52.49% dead neurons
layer 1: 68.43% dead neurons
layer 0: 52.48% dead neurons
layer 1: 67.62% dead neurons
layer 0: 52.49% dead neurons
layer 1: 68.43% dead neurons
layer 0: 52.47% dead neurons
layer 1: 67.57% dead neurons
layer 0: 52.48% dead neurons
layer 1: 68.37% dead neurons
---------------------------------
epoch: 60
accuracy: 0.9353571428571429
layer 0: 52.46% dead neurons
layer 1: 67.61% dead neurons
layer 0: 52.46% dead neurons
layer 1: 68.10% dead neurons
layer 0: 52.43% dead neurons
layer 1: 67.60% dead neurons
layer 0: 52.42% dead neurons
layer 1: 67.77% dead neurons
layer 0: 52.39% dead neurons
layer 1: 67.50% dead neurons
layer 0: 52.37% dead neurons
layer 1: 67.54% dead neurons
layer 0: 52.35% dead neurons
layer 1: 67.35% dead neurons
layer 0: 52.33% dead neurons
layer 1: 67.34% dead neurons
layer 0: 52.32% dead neurons
layer 1: 67.20% dead neurons
layer 0: 52.30% dead neurons
layer 1: 67.18% dead neurons
---------------------------------
epoch: 70
accuracy: 0.944047619047619
layer 0: 52.29% dead neurons
layer 1: 67.06% dead neurons
layer 0: 52.27% dead neurons
layer 1: 67.02% dead neurons
layer 0: 52.26% dead neurons
layer 1: 66.92% dead neurons
layer 0: 52.23% dead neurons
layer 1: 66.88% dead neurons
layer 0: 52.22% dead neurons
layer 1: 66.79% dead neurons
layer 0: 52.20% dead neurons
layer 1: 66.73% dead neurons
layer 0: 52.19% dead neurons
layer 1: 66.64% dead neurons
layer 0: 52.17% dead neurons
layer 1: 66.60% dead neurons
layer 0: 52.16% dead neurons
layer 1: 66.51% dead neurons
layer 0: 52.15% dead neurons
layer 1: 66.47% dead neurons
---------------------------------
epoch: 80
accuracy: 0.945595238095238
layer 0: 52.13% dead neurons
layer 1: 66.39% dead neurons
layer 0: 52.12% dead neurons
layer 1: 66.33% dead neurons
layer 0: 52.11% dead neurons
layer 1: 66.27% dead neurons
layer 0: 52.09% dead neurons
layer 1: 66.21% dead neurons
layer 0: 52.08% dead neurons
layer 1: 66.15% dead neurons
layer 0: 52.06% dead neurons
layer 1: 66.10% dead neurons
layer 0: 52.05% dead neurons
layer 1: 66.05% dead neurons
layer 0: 52.03% dead neurons
layer 1: 66.01% dead neurons
layer 0: 52.02% dead neurons
layer 1: 65.96% dead neurons
layer 0: 52.01% dead neurons
layer 1: 65.92% dead neurons
---------------------------------
epoch: 90
accuracy: 0.9471428571428572
layer 0: 52.00% dead neurons
layer 1: 65.86% dead neurons
layer 0: 51.98% dead neurons
layer 1: 65.82% dead neurons
layer 0: 51.97% dead neurons
layer 1: 65.77% dead neurons
layer 0: 51.96% dead neurons
layer 1: 65.73% dead neurons
layer 0: 51.95% dead neurons
layer 1: 65.68% dead neurons
layer 0: 51.93% dead neurons
layer 1: 65.64% dead neurons
layer 0: 51.92% dead neurons
layer 1: 65.58% dead neurons
layer 0: 51.91% dead neurons
layer 1: 65.54% dead neurons
layer 0: 51.90% dead neurons
layer 1: 65.49% dead neurons
layer 0: 51.89% dead neurons
layer 1: 65.46% dead neurons
---------------------------------
epoch: 100
accuracy: 0.9483333333333334
layer 0: 51.88% dead neurons
layer 1: 65.41% dead neurons
layer 0: 51.87% dead neurons
layer 1: 65.37% dead neurons
layer 0: 51.86% dead neurons
layer 1: 65.33% dead neurons
layer 0: 51.84% dead neurons
layer 1: 65.29% dead neurons
layer 0: 51.84% dead neurons
layer 1: 65.24% dead neurons
layer 0: 51.82% dead neurons
layer 1: 65.21% dead neurons
layer 0: 51.82% dead neurons
layer 1: 65.16% dead neurons
layer 0: 51.81% dead neurons
layer 1: 65.13% dead neurons
layer 0: 51.81% dead neurons
layer 1: 65.07% dead neurons
layer 0: 51.79% dead neurons
layer 1: 65.04% dead neurons
---------------------------------
epoch: 110
accuracy: 0.9497619047619048
layer 0: 51.79% dead neurons
layer 1: 64.99% dead neurons
layer 0: 51.77% dead neurons
layer 1: 64.96% dead neurons
layer 0: 51.77% dead neurons
layer 1: 64.90% dead neurons
layer 0: 51.75% dead neurons
layer 1: 64.87% dead neurons
layer 0: 51.75% dead neurons
layer 1: 64.82% dead neurons
layer 0: 51.74% dead neurons
layer 1: 64.79% dead neurons
layer 0: 51.74% dead neurons
layer 1: 64.72% dead neurons
layer 0: 51.72% dead neurons
layer 1: 64.70% dead neurons
layer 0: 51.72% dead neurons
layer 1: 64.63% dead neurons
layer 0: 51.70% dead neurons
layer 1: 64.62% dead neurons
---------------------------------
epoch: 120
accuracy: 0.950595238095238
layer 0: 51.70% dead neurons
layer 1: 64.55% dead neurons
layer 0: 51.68% dead neurons
layer 1: 64.53% dead neurons
layer 0: 51.68% dead neurons
layer 1: 64.47% dead neurons
layer 0: 51.66% dead neurons
layer 1: 64.46% dead neurons
layer 0: 51.65% dead neurons
layer 1: 64.39% dead neurons
layer 0: 51.64% dead neurons
layer 1: 64.38% dead neurons
layer 0: 51.64% dead neurons
layer 1: 64.31% dead neurons
layer 0: 51.63% dead neurons
layer 1: 64.31% dead neurons
layer 0: 51.62% dead neurons
layer 1: 64.24% dead neurons
layer 0: 51.61% dead neurons
layer 1: 64.24% dead neurons
---------------------------------
epoch: 130
accuracy: 0.9515476190476191
layer 0: 51.60% dead neurons
layer 1: 64.17% dead neurons
layer 0: 51.59% dead neurons
layer 1: 64.17% dead neurons
layer 0: 51.59% dead neurons
layer 1: 64.09% dead neurons
layer 0: 51.58% dead neurons
layer 1: 64.09% dead neurons
layer 0: 51.58% dead neurons
layer 1: 64.00% dead neurons
layer 0: 51.56% dead neurons
layer 1: 64.01% dead neurons
layer 0: 51.56% dead neurons
layer 1: 63.93% dead neurons
layer 0: 51.55% dead neurons
layer 1: 63.94% dead neurons
layer 0: 51.55% dead neurons
layer 1: 63.87% dead neurons
layer 0: 51.54% dead neurons
layer 1: 63.89% dead neurons
---------------------------------
epoch: 140
accuracy: 0.9520238095238095
layer 0: 51.54% dead neurons
layer 1: 63.79% dead neurons
layer 0: 51.54% dead neurons
layer 1: 63.82% dead neurons
layer 0: 51.53% dead neurons
layer 1: 63.73% dead neurons
layer 0: 51.53% dead neurons
layer 1: 63.75% dead neurons
layer 0: 51.52% dead neurons
layer 1: 63.67% dead neurons
layer 0: 51.51% dead neurons
layer 1: 63.69% dead neurons
layer 0: 51.51% dead neurons
layer 1: 63.61% dead neurons
layer 0: 51.50% dead neurons
layer 1: 63.63% dead neurons
layer 0: 51.50% dead neurons
layer 1: 63.55% dead neurons
layer 0: 51.49% dead neurons
layer 1: 63.58% dead neurons
---------------------------------
epoch: 150
accuracy: 0.9526190476190476
layer 0: 51.48% dead neurons
layer 1: 63.50% dead neurons
layer 0: 51.48% dead neurons
layer 1: 63.53% dead neurons
layer 0: 51.48% dead neurons
layer 1: 63.44% dead neurons
layer 0: 51.47% dead neurons
layer 1: 63.48% dead neurons
layer 0: 51.47% dead neurons
layer 1: 63.39% dead neurons
layer 0: 51.46% dead neurons
layer 1: 63.43% dead neurons
layer 0: 51.46% dead neurons
layer 1: 63.35% dead neurons
layer 0: 51.45% dead neurons
layer 1: 63.38% dead neurons
layer 0: 51.44% dead neurons
layer 1: 63.30% dead neurons
layer 0: 51.44% dead neurons
layer 1: 63.34% dead neurons
---------------------------------
epoch: 160
accuracy: 0.9530952380952381
layer 0: 51.43% dead neurons
layer 1: 63.25% dead neurons
layer 0: 51.43% dead neurons
layer 1: 63.29% dead neurons
layer 0: 51.42% dead neurons
layer 1: 63.20% dead neurons
layer 0: 51.41% dead neurons
layer 1: 63.24% dead neurons
layer 0: 51.41% dead neurons
layer 1: 63.15% dead neurons
layer 0: 51.40% dead neurons
layer 1: 63.19% dead neurons
layer 0: 51.39% dead neurons
layer 1: 63.11% dead neurons
layer 0: 51.38% dead neurons
layer 1: 63.15% dead neurons
layer 0: 51.38% dead neurons
layer 1: 63.06% dead neurons
layer 0: 51.37% dead neurons
layer 1: 63.10% dead neurons
---------------------------------
epoch: 170
accuracy: 0.9538095238095238
layer 0: 51.37% dead neurons
layer 1: 63.03% dead neurons
layer 0: 51.37% dead neurons
layer 1: 63.06% dead neurons
layer 0: 51.36% dead neurons
layer 1: 62.97% dead neurons
layer 0: 51.35% dead neurons
layer 1: 63.02% dead neurons
layer 0: 51.35% dead neurons
layer 1: 62.93% dead neurons
layer 0: 51.35% dead neurons
layer 1: 62.97% dead neurons
layer 0: 51.34% dead neurons
layer 1: 62.89% dead neurons
layer 0: 51.34% dead neurons
layer 1: 62.92% dead neurons
layer 0: 51.34% dead neurons
layer 1: 62.84% dead neurons
layer 0: 51.34% dead neurons
layer 1: 62.88% dead neurons
---------------------------------
epoch: 180
accuracy: 0.9547619047619048
layer 0: 51.33% dead neurons
layer 1: 62.80% dead neurons
layer 0: 51.33% dead neurons
layer 1: 62.85% dead neurons
layer 0: 51.33% dead neurons
layer 1: 62.76% dead neurons
layer 0: 51.31% dead neurons
layer 1: 62.81% dead neurons
layer 0: 51.32% dead neurons
layer 1: 62.72% dead neurons
layer 0: 51.31% dead neurons
layer 1: 62.76% dead neurons
layer 0: 51.31% dead neurons
layer 1: 62.68% dead neurons
layer 0: 51.31% dead neurons
layer 1: 62.72% dead neurons
layer 0: 51.30% dead neurons
layer 1: 62.63% dead neurons
layer 0: 51.30% dead neurons
layer 1: 62.68% dead neurons
---------------------------------
epoch: 190
accuracy: 0.9557142857142857
layer 0: 51.29% dead neurons
layer 1: 62.59% dead neurons
layer 0: 51.29% dead neurons
layer 1: 62.64% dead neurons
layer 0: 51.28% dead neurons
layer 1: 62.54% dead neurons
layer 0: 51.27% dead neurons
layer 1: 62.60% dead neurons
layer 0: 51.28% dead neurons
layer 1: 62.50% dead neurons
layer 0: 51.27% dead neurons
layer 1: 62.56% dead neurons
layer 0: 51.27% dead neurons
layer 1: 62.47% dead neurons
layer 0: 51.27% dead neurons
layer 1: 62.53% dead neurons
layer 0: 51.26% dead neurons
layer 1: 62.43% dead neurons
layer 0: 51.26% dead neurons
layer 1: 62.49% dead neurons
---------------------------------
epoch: 200
accuracy: 0.9552380952380952
layer 0: 51.26% dead neurons
layer 1: 62.40% dead neurons
layer 0: 51.25% dead neurons
layer 1: 62.46% dead neurons
layer 0: 51.25% dead neurons
layer 1: 62.37% dead neurons
layer 0: 51.25% dead neurons
layer 1: 62.43% dead neurons
layer 0: 51.24% dead neurons
layer 1: 62.33% dead neurons
layer 0: 51.24% dead neurons
layer 1: 62.40% dead neurons
layer 0: 51.24% dead neurons
layer 1: 62.30% dead neurons
layer 0: 51.24% dead neurons
layer 1: 62.37% dead neurons
layer 0: 51.23% dead neurons
layer 1: 62.27% dead neurons
layer 0: 51.23% dead neurons
layer 1: 62.33% dead neurons
---------------------------------
epoch: 210
accuracy: 0.9554761904761905
layer 0: 51.22% dead neurons
layer 1: 62.24% dead neurons
layer 0: 51.22% dead neurons
layer 1: 62.30% dead neurons
layer 0: 51.21% dead neurons
layer 1: 62.21% dead neurons
layer 0: 51.22% dead neurons
layer 1: 62.27% dead neurons
layer 0: 51.21% dead neurons
layer 1: 62.18% dead neurons
layer 0: 51.21% dead neurons
layer 1: 62.24% dead neurons
layer 0: 51.20% dead neurons
layer 1: 62.14% dead neurons
layer 0: 51.20% dead neurons
layer 1: 62.21% dead neurons
layer 0: 51.20% dead neurons
layer 1: 62.11% dead neurons
layer 0: 51.20% dead neurons
layer 1: 62.18% dead neurons
---------------------------------
epoch: 220
accuracy: 0.9558333333333333
layer 0: 51.19% dead neurons
layer 1: 62.09% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.15% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.06% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.13% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.04% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.11% dead neurons
layer 0: 51.18% dead neurons
layer 1: 62.02% dead neurons
layer 0: 51.19% dead neurons
layer 1: 62.09% dead neurons
layer 0: 51.18% dead neurons
layer 1: 62.00% dead neurons
layer 0: 51.18% dead neurons
layer 1: 62.06% dead neurons
---------------------------------
epoch: 230
accuracy: 0.955952380952381
layer 0: 51.18% dead neurons
layer 1: 61.98% dead neurons
layer 0: 51.17% dead neurons
layer 1: 62.04% dead neurons
layer 0: 51.17% dead neurons
layer 1: 61.96% dead neurons
layer 0: 51.17% dead neurons
layer 1: 62.02% dead neurons
layer 0: 51.16% dead neurons
layer 1: 61.94% dead neurons
layer 0: 51.16% dead neurons
layer 1: 62.00% dead neurons
layer 0: 51.16% dead neurons
layer 1: 61.92% dead neurons
layer 0: 51.16% dead neurons
layer 1: 61.98% dead neurons
layer 0: 51.15% dead neurons
layer 1: 61.91% dead neurons
layer 0: 51.15% dead neurons
layer 1: 61.96% dead neurons
---------------------------------
epoch: 240
accuracy: 0.9564285714285714
layer 0: 51.15% dead neurons
layer 1: 61.89% dead neurons
layer 0: 51.15% dead neurons
layer 1: 61.94% dead neurons
layer 0: 51.14% dead neurons
layer 1: 61.87% dead neurons
layer 0: 51.14% dead neurons
layer 1: 61.92% dead neurons
layer 0: 51.14% dead neurons
layer 1: 61.85% dead neurons
layer 0: 51.13% dead neurons
layer 1: 61.90% dead neurons
layer 0: 51.13% dead neurons
layer 1: 61.84% dead neurons
layer 0: 51.13% dead neurons
layer 1: 61.88% dead neurons
layer 0: 51.12% dead neurons
layer 1: 61.82% dead neurons
layer 0: 51.12% dead neurons
layer 1: 61.86% dead neurons
---------------------------------
epoch: 250
accuracy: 0.9567857142857142
layer 0: 51.11% dead neurons
layer 1: 61.79% dead neurons
layer 0: 51.11% dead neurons
layer 1: 61.84% dead neurons
layer 0: 51.11% dead neurons
layer 1: 61.78% dead neurons
layer 0: 51.10% dead neurons
layer 1: 61.82% dead neurons
layer 0: 51.10% dead neurons
layer 1: 61.76% dead neurons
layer 0: 51.10% dead neurons
layer 1: 61.80% dead neurons
layer 0: 51.09% dead neurons
layer 1: 61.74% dead neurons
layer 0: 51.09% dead neurons
layer 1: 61.78% dead neurons
layer 0: 51.09% dead neurons
layer 1: 61.73% dead neurons
layer 0: 51.08% dead neurons
layer 1: 61.76% dead neurons
---------------------------------
epoch: 260
accuracy: 0.9569047619047619
layer 0: 51.08% dead neurons
layer 1: 61.72% dead neurons
layer 0: 51.08% dead neurons
layer 1: 61.75% dead neurons
layer 0: 51.08% dead neurons
layer 1: 61.70% dead neurons
layer 0: 51.07% dead neurons
layer 1: 61.73% dead neurons
layer 0: 51.08% dead neurons
layer 1: 61.68% dead neurons
layer 0: 51.07% dead neurons
layer 1: 61.72% dead neurons
layer 0: 51.07% dead neurons
layer 1: 61.66% dead neurons
layer 0: 51.06% dead neurons
layer 1: 61.70% dead neurons
layer 0: 51.06% dead neurons
layer 1: 61.65% dead neurons
layer 0: 51.06% dead neurons
layer 1: 61.68% dead neurons
---------------------------------
epoch: 270
accuracy: 0.9572619047619048
layer 0: 51.05% dead neurons
layer 1: 61.63% dead neurons
layer 0: 51.05% dead neurons
layer 1: 61.67% dead neurons
layer 0: 51.05% dead neurons
layer 1: 61.62% dead neurons
layer 0: 51.05% dead neurons
layer 1: 61.66% dead neurons
layer 0: 51.04% dead neurons
layer 1: 61.61% dead neurons
layer 0: 51.04% dead neurons
layer 1: 61.64% dead neurons
layer 0: 51.03% dead neurons
layer 1: 61.59% dead neurons
layer 0: 51.03% dead neurons
layer 1: 61.62% dead neurons
layer 0: 51.02% dead neurons
layer 1: 61.57% dead neurons
layer 0: 51.02% dead neurons
layer 1: 61.60% dead neurons
---------------------------------
epoch: 280
accuracy: 0.9577380952380953
layer 0: 51.02% dead neurons
layer 1: 61.56% dead neurons
layer 0: 51.02% dead neurons
layer 1: 61.59% dead neurons
layer 0: 51.01% dead neurons
layer 1: 61.54% dead neurons
layer 0: 51.01% dead neurons
layer 1: 61.57% dead neurons
layer 0: 51.00% dead neurons
layer 1: 61.52% dead neurons
layer 0: 51.01% dead neurons
layer 1: 61.55% dead neurons
layer 0: 51.00% dead neurons
layer 1: 61.51% dead neurons
layer 0: 51.00% dead neurons
layer 1: 61.54% dead neurons
layer 0: 50.99% dead neurons
layer 1: 61.50% dead neurons
layer 0: 51.00% dead neurons
layer 1: 61.52% dead neurons
---------------------------------
epoch: 290
accuracy: 0.9580952380952381
layer 0: 50.99% dead neurons
layer 1: 61.49% dead neurons
layer 0: 50.99% dead neurons
layer 1: 61.51% dead neurons
layer 0: 50.98% dead neurons
layer 1: 61.48% dead neurons
layer 0: 50.98% dead neurons
layer 1: 61.50% dead neurons
layer 0: 50.98% dead neurons
layer 1: 61.46% dead neurons
layer 0: 50.98% dead neurons
layer 1: 61.48% dead neurons
layer 0: 50.97% dead neurons
layer 1: 61.45% dead neurons
layer 0: 50.97% dead neurons
layer 1: 61.48% dead neurons
layer 0: 50.97% dead neurons
layer 1: 61.44% dead neurons


 Highest Accuracy:
	Epoch # = 286
	Accuracy = 0.9583333333333334

# Prediction

In [47]:
base_model_predictions = base_model.predict(X_data=digit_test_data_scaled)
base_model_predictions.shape

(28000,)

In [48]:
# with open("/Users/ronitmathur/Desktop/ML/Feed-Forward_NN/base_model_predictions", "w") as base_model_output_file:
#     base_model_output_file.write()

# 1. Flatten and ensure predictions are integers (e.g., 0 instead of 0.0)
final_predictions = np.asarray(base_model_predictions).flatten().astype(int)

# 2. Create the DataFrame and shift the index to start at 1
df = pd.DataFrame({'Label': final_predictions})
df.index = df.index + 1

# 3. Save to a CSV file matching the format perfectly
curr_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
df.to_csv(f"/Users/ronitmathur/Desktop/ML/Feed-Forward_NN/base_model_submission_{curr_time}.csv", index_label='ImageId')